# **Cointab Assignment**

In [1121]:
# Importing required libraries
import pandas as pd
import numpy as np
import math

In [1122]:
# Loading all datasets
order = pd.read_excel("Company X - Order Report.xlsx")
pincode = pd.read_excel("Company X - Pincode Zones.xlsx")
SKU = pd.read_excel("Company X - SKU Master.xlsx")
invoice = pd.read_excel("Courier Company - Invoice.xlsx")
rates = pd.read_excel("Courier Company - Rates.xlsx")

In [1123]:
order.head()

   ExternOrderNo            SKU  Order Qty Payment Mode  Item Price(Per Qty.)
0     2001827036  8904223818706          1          COD                   233
1     2001827036  8904223819093          1          COD                   233
2     2001827036  8904223819109          1          COD                   233
3     2001827036  8904223818430          1          COD                   470
4     2001827036  8904223819277          1          COD                   233

In [1124]:
order.shape

(400, 5)

In [1125]:
# calculating total order price
order["total order price in Rs"] = order["Order Qty"]*order["Item Price(Per Qty.)"]
order.head()

,ExternOrderNo,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs
0,2001827036,8904223818706,1,COD,233,233
1,2001827036,8904223819093,1,COD,233,233
2,2001827036,8904223819109,1,COD,233,233
3,2001827036,8904223818430,1,COD,470,470
4,2001827036,8904223819277,1,COD,233,233

In [1126]:
# COD charges

charge = []
for x in order["Payment Mode"]:
  if x == "COD":
    for y in order["total order price in Rs"]:
      if y<= 300:
        charge.append(15)
      else:
        charge.append(y*0.05)
  else:
    charge.append(0)
charge[0:10]

[15, 15, 15, 23.5, 15, 32.95, 57.0, 17.5, 727.2, 781.4000000000001]

In [1127]:
order["COD charges in Rs as per X"] = charge[0:400]
order["COD charges in Rs as per X"] = np.where(order["Payment Mode"]=="Prepaid",0,order["COD charges in Rs as per X"])

In [1128]:
order.shape

(400, 7)

In [1129]:
pincode.head()

   Warehouse Pincode  Customer Pincode Zone
0             121003            507101    d
1             121003            486886    d
2             121003            532484    d
3             121003            143001    b
4             121003            515591    d

In [1130]:
pincode.shape

(124, 3)

In [1131]:
pincode.drop_duplicates(subset = "Customer Pincode", inplace=True)

In [1132]:
SKU.head()

             SKU  Weight (g)
0  8904223815682         210
1  8904223815859         165
2  8904223815866         113
3  8904223815873          65
4  8904223816214         120

In [1133]:
SKU.shape

(66, 2)

In [1134]:
SKU.drop_duplicates(subset="SKU", inplace=True)

In [1135]:
rates.head()

,Zone,Weight Slabs,Forward Fixed Charge,Forward Additional Weight Slab Charge,RTO Fixed Charge,RTO Additional Weight Slab Charge
0,A,0.25,29.5,23.6,13.6,23.6
1,B,0.50,33.0,28.3,20.5,28.3
2,C,0.75,40.1,38.9,31.9,38.9
3,D,1.25,45.4,44.8,41.3,44.8
4,E,1.50,56.6,55.5,50.7,55.5

In [1136]:
invoice.head()

,AWB Code,Order ID,Charged Weight,Warehouse Pincode,Customer Pincode,Zone,Type of Shipment,Billing Amount (Rs.)
0,1091117222124,2001806232,1.30,121003,507101,d,Forward charges,140.0
1,1091117222194,2001806273,1.00,121003,486886,d,Forward charges,101.2
2,1091117222931,2001806408,2.50,121003,532484,d,Forward charges,224.6
3,1091117223244,2001806458,1.00,121003,143001,b,Forward charges,61.3
4,1091117229345,2001807012,0.15,121003,515591,d,Forward charges,45.4

In [1137]:
invoice.shape

(124, 8)

In [1138]:
merged_data1 = pd.merge(order, SKU, on="SKU", how="left")

In [1139]:
#Calculate total weight
merged_data1["total_weight in KG as per X"] = merged_data1["Order Qty"] * merged_data1["Weight (g)"] /1000
merged_data = merged_data1.rename(columns={'ExternOrderNo':"Order ID"})
merged_data

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs,COD charges in Rs as per X,Weight (g),total_weight in KG as per X
0,2001827036,8904223818706,1,COD,233,233,15.00,127,0.127
1,2001827036,8904223819093,1,COD,233,233,15.00,150,0.150
2,2001827036,8904223819109,1,COD,233,233,15.00,100,0.100
3,2001827036,8904223818430,1,COD,470,470,23.50,165,0.165
4,2001827036,8904223819277,1,COD,233,233,15.00,350,0.350
...,...,...,...,...,...,...,...,...,...
395,2001806229,8904223818942,1,COD,286,286,15.00,133,0.133
396,2001806229,8904223818850,1,COD,563,563,28.15,240,0.240
397,2001806226,8904223818850,2,COD,1125,2250,112.50,240,0.480
398,2001806210,8904223816214,1,COD,402,402,20.10,120,0.120
399,2001806210,8904223818874,1,COD,922,922,46.10,100,0.100

In [1140]:
invoice['Warehouse Pincode'].unique()

array([121003])

In [1141]:
merged_data2 = invoice.merge(pincode , on= "Customer Pincode", how = "left")

In [1142]:
merged_data3 = merged_data2.drop(columns=["Warehouse Pincode_x", "Warehouse Pincode_y"])

In [1143]:
merged_data3["Zone_comparision"] = merged_data3["Zone_x"] == merged_data3["Zone_y"]

In [1144]:
merged_data3.rename(columns={'Zone_x': 'Zone as per courier', 'Zone_y': 'Zone as per X'}, inplace=True)



> Merging Invoice and Order Report

In [1145]:
merged_data4 = merged_data.merge(merged_data3, on="Order ID", how="inner")
# merged_data4

In [1146]:
merged_data4.rename({'Charged Weight':'total weight as per courier'}, axis = 1, inplace = True)

In [1147]:
merged_data5 = merged_data4.drop(columns= ["Zone_comparision",'Customer Pincode'])
merged_data5

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs,COD charges in Rs as per X,Weight (g),total_weight in KG as per X,AWB Code,total weight as per courier,Zone as per courier,Type of Shipment,Billing Amount (Rs.),Zone as per X
0,2001827036,8904223818706,1,COD,233,233,15.00,127,0.127,1091122418320,1.60,b,Forward charges,117.9,e
1,2001827036,8904223819093,1,COD,233,233,15.00,150,0.150,1091122418320,1.60,b,Forward charges,117.9,e
2,2001827036,8904223819109,1,COD,233,233,15.00,100,0.100,1091122418320,1.60,b,Forward charges,117.9,e
3,2001827036,8904223818430,1,COD,470,470,23.50,165,0.165,1091122418320,1.60,b,Forward charges,117.9,e
4,2001827036,8904223819277,1,COD,233,233,15.00,350,0.350,1091122418320,1.60,b,Forward charges,117.9,e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,2001806229,8904223818942,1,COD,286,286,15.00,133,0.133,1091117222080,0.71,d,Forward charges,90.2,d
396,2001806229,8904223818850,1,COD,563,563,28.15,240,0.240,1091117222080,0.71,d,Forward charges,90.2,d
397,2001806226,8904223818850,2,COD,1125,2250,112.50,240,0.480,1091117222065,0.68,d,Forward charges,90.2,d
398,2001806210,8904223816214,1,COD,402,402,20.10,120,0.120,1091117221940,2.92,b,Forward charges,174.5,b
399,2001806210,8904223818874,1,COD,922,922,46.10,100,0.100,1091117221940,2.92,b,Forward charges,174.5,b

In [1148]:
merged_data5.shape

(400, 15)

In [1149]:
merged_data5.isna().sum()

Order ID                       0
SKU                            0
Order Qty                      0
Payment Mode                   0
Item Price(Per Qty.)           0
total order price in Rs        0
COD charges in Rs as per X     0
Weight (g)                     0
total_weight in KG as per X    0
AWB Code                       0
total weight as per courier    0
Zone as per courier            0
Type of Shipment               0
Billing Amount (Rs.)           0
Zone as per X                  0
dtype: int64

In [1150]:
merged_data5["Zone as per X"].unique()

array(['e', 'd', 'b'], dtype=object)

In [1151]:
zonexb = merged_data5[merged_data5["Zone as per X"] == "b"]
zonexb.shape

(238, 15)

In [1152]:
zonexd = merged_data5[merged_data5["Zone as per X"] == "d"]
zonexd.shape

(136, 15)

In [1153]:
zonexe = merged_data5[merged_data5["Zone as per X"] == "e"]
zonexe.shape

(26, 15)

In [1154]:
# weight slab for zone_b as per X
def weight_slab(weight):
  i = round(weight%1,1)
  if i == 0.0:
    return weight
  elif i > 0.5:
    return int(weight)+1
  else:
    return int(weight)+0.5

zonexb["weight slab as per X (kg)"]= zonexb["total_weight in KG as per X"].apply(weight_slab)
zonexb

<ipython-input-1154-c2faa23fc018>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zonexb["weight slab as per X (kg)"]= zonexb["total_weight in KG as per X"].apply(weight_slab)

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs,COD charges in Rs as per X,Weight (g),total_weight in KG as per X,AWB Code,total weight as per courier,Zone as per courier,Type of Shipment,Billing Amount (Rs.),Zone as per X,weight slab as per X (kg)
16,2001822466,8904223819468,2,COD,1205,2410,120.5,240,0.480,1091121305541,1.10,d,Forward charges,135.0,b,0.5
17,2001822466,8904223819291,8,COD,7814,62512,3125.6,112,0.896,1091121305541,1.10,d,Forward charges,135.0,b,1.0
18,2001821995,8904223819130,1,Prepaid,251,251,0.0,350,0.350,1091121183730,0.50,d,Forward charges,45.4,b,0.5
19,2001821995,8904223818706,1,Prepaid,233,233,0.0,127,0.127,1091121183730,0.50,d,Forward charges,45.4,b,0.5
20,2001821766,8904223818591,2,COD,473,946,47.3,120,0.240,1091121034641,0.20,d,Forward charges,63.4,b,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,2001806304,8904223818850,1,Prepaid,563,563,0.0,240,0.240,1091117222360,0.71,d,Forward charges,90.2,b,0.5
390,2001806233,8904223819161,1,Prepaid,810,810,0.0,115,0.115,1091117222135,0.78,b,Forward charges,61.3,b,0.5
391,2001806233,8904223819260,1,Prepaid,676,676,0.0,130,0.130,1091117222135,0.78,b,Forward charges,61.3,b,0.5
398,2001806210,8904223816214,1,COD,402,402,20.1,120,0.120,1091117221940,2.92,b,Forward charges,174.5,b,0.5
399,2001806210,8904223818874,1,COD,922,922,46.1,100,0.100,1091117221940,2.92,b,Forward charges,174.5,b,0.5

In [1155]:
# weight slab for zone_d as per X
def weight_slab(weight):
  i = round(weight%1.25,2)
  if i == 0.00:
    return weight
  elif weight<1.25:
    return 1.25
  else:
    return (weight//1.25)*1.25+1.25

zonexd["weight slab as per X (kg)"]= zonexd["total_weight in KG as per X"].apply(weight_slab)
zonexd.head()

<ipython-input-1155-7b3989618acb>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zonexd["weight slab as per X (kg)"]= zonexd["total_weight in KG as per X"].apply(weight_slab)

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs,COD charges in Rs as per X,Weight (g),total_weight in KG as per X,AWB Code,total weight as per courier,Zone as per courier,Type of Shipment,Billing Amount (Rs.),Zone as per X,weight slab as per X (kg)
8,2001825261,8904223819024,4,Prepaid,3636,14544,0.0,112,0.448,1091121981575,1.6,d,Forward and RTO charges,345.0,d,1.25
9,2001825261,8904223819291,4,Prepaid,3907,15628,0.0,112,0.448,1091121981575,1.6,d,Forward and RTO charges,345.0,d,1.25
10,2001825261,8904223818638,3,Prepaid,855,2565,0.0,137,0.411,1091121981575,1.6,d,Forward and RTO charges,345.0,d,1.25
11,2001825261,8904223818669,1,Prepaid,301,301,0.0,240,0.240,1091121981575,1.6,d,Forward and RTO charges,345.0,d,1.25
12,2001825261,SACHETS001,1,Prepaid,350,350,0.0,10,0.010,1091121981575,1.6,d,Forward and RTO charges,345.0,d,1.25

In [1156]:
# weight slab for zone_e as per X
def weight_slab(weight):
  i = round(weight%1.5,2)
  if i == 0.00:
    return weight
  elif i <1.5:
    return 1.5
  else:
    return (weight//1.5)*1.5+1.5

zonexe["weight slab as per X (kg)"]= zonexe["total_weight in KG as per X"].apply(weight_slab)
zonexe.head()

<ipython-input-1156-2f3378b0c75e>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zonexe["weight slab as per X (kg)"]= zonexe["total_weight in KG as per X"].apply(weight_slab)

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs,COD charges in Rs as per X,Weight (g),total_weight in KG as per X,AWB Code,total weight as per courier,Zone as per courier,Type of Shipment,Billing Amount (Rs.),Zone as per X,weight slab as per X (kg)
0,2001827036,8904223818706,1,COD,233,233,15.0,127,0.127,1091122418320,1.6,b,Forward charges,117.9,e,1.5
1,2001827036,8904223819093,1,COD,233,233,15.0,150,0.150,1091122418320,1.6,b,Forward charges,117.9,e,1.5
2,2001827036,8904223819109,1,COD,233,233,15.0,100,0.100,1091122418320,1.6,b,Forward charges,117.9,e,1.5
3,2001827036,8904223818430,1,COD,470,470,23.5,165,0.165,1091122418320,1.6,b,Forward charges,117.9,e,1.5
4,2001827036,8904223819277,1,COD,233,233,15.0,350,0.350,1091122418320,1.6,b,Forward charges,117.9,e,1.5

In [1157]:
#Expected charge for X in b zone
fwd_fxd = 33
fwd_add = 28.3
rto_fxd = 20.5
rto_add = 28.3
weight_slab = zonexb["weight slab as per X (kg)"]
add_weight = (weight_slab-0.5)/0.5
zonexb["expected charges by X in Rs"] = 0
zonexb["expected charges by X in Rs"] = np.where(zonexb['Type of Shipment'] == 'Forward charges',(fwd_fxd + add_weight*fwd_add), zonexb["expected charges by X in Rs"])
zonexb["expected charges by X in Rs"] = np.where(zonexb["Type of Shipment"]== "Forward and RTO charges",(fwd_fxd + rto_fxd + add_weight*(fwd_add + rto_add)) ,zonexb["expected charges by X in Rs"])
zonexb.head()

<ipython-input-1157-1944525f5409>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zonexb["expected charges by X in Rs"] = 0
<ipython-input-1157-1944525f5409>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zonexb["expected charges by X in Rs"] = np.where(zonexb['Type of Shipment'] == 'Forward charges',(fwd_fxd + add_weight*fwd_add), zonexb["expected charges by X in Rs"])
<ipython-input-1157-1944525f5409>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zonexb["expected charges by X in Rs"] = np.where(zonexb["Type of Shipment"]== "Forward and RTO charges",(fwd_fxd + rto_fxd + add_weight*(fwd_add + rto_add)) ,zonexb["expected charges by X in Rs"])

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs,COD charges in Rs as per X,Weight (g),total_weight in KG as per X,AWB Code,total weight as per courier,Zone as per courier,Type of Shipment,Billing Amount (Rs.),Zone as per X,weight slab as per X (kg),expected charges by X in Rs
16,2001822466,8904223819468,2,COD,1205,2410,120.5,240,0.480,1091121305541,1.1,d,Forward charges,135.0,b,0.5,33.0
17,2001822466,8904223819291,8,COD,7814,62512,3125.6,112,0.896,1091121305541,1.1,d,Forward charges,135.0,b,1.0,61.3
18,2001821995,8904223819130,1,Prepaid,251,251,0.0,350,0.350,1091121183730,0.5,d,Forward charges,45.4,b,0.5,33.0
19,2001821995,8904223818706,1,Prepaid,233,233,0.0,127,0.127,1091121183730,0.5,d,Forward charges,45.4,b,0.5,33.0
20,2001821766,8904223818591,2,COD,473,946,47.3,120,0.240,1091121034641,0.2,d,Forward charges,63.4,b,0.5,33.0

In [1158]:
#Expected charge for X in d zone
fwd_fxd = 45.4
fwd_add = 44.8
rto_fxd = 41.3
rto_add = 44.8
weight_slab = zonexd["weight slab as per X (kg)"]
add_weight = (weight_slab-1.25)/1.25
zonexd["expected charges by X in Rs"] = 0
zonexd["expected charges by X in Rs"] = np.where(zonexd['Type of Shipment'] == 'Forward charges',(fwd_fxd + add_weight*fwd_add), zonexd["expected charges by X in Rs"])
zonexd["expected charges by X in Rs"] = np.where(zonexd["Type of Shipment"]== "Forward and RTO charges",(fwd_fxd + rto_fxd + add_weight*(fwd_add + rto_add)) ,zonexd["expected charges by X in Rs"])
zonexd.head()

<ipython-input-1158-f95c3355a474>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zonexd["expected charges by X in Rs"] = 0
<ipython-input-1158-f95c3355a474>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zonexd["expected charges by X in Rs"] = np.where(zonexd['Type of Shipment'] == 'Forward charges',(fwd_fxd + add_weight*fwd_add), zonexd["expected charges by X in Rs"])
<ipython-input-1158-f95c3355a474>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zonexd["expected charges by X in Rs"] = np.where(zonexd["Type of Shipment"]== "Forward and RTO charges",(fwd_fxd + rto_fxd + add_weight*(fwd_add + rto_add)) ,zonexd["expected charges by X in Rs"])

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs,COD charges in Rs as per X,Weight (g),total_weight in KG as per X,AWB Code,total weight as per courier,Zone as per courier,Type of Shipment,Billing Amount (Rs.),Zone as per X,weight slab as per X (kg),expected charges by X in Rs
8,2001825261,8904223819024,4,Prepaid,3636,14544,0.0,112,0.448,1091121981575,1.6,d,Forward and RTO charges,345.0,d,1.25,86.7
9,2001825261,8904223819291,4,Prepaid,3907,15628,0.0,112,0.448,1091121981575,1.6,d,Forward and RTO charges,345.0,d,1.25,86.7
10,2001825261,8904223818638,3,Prepaid,855,2565,0.0,137,0.411,1091121981575,1.6,d,Forward and RTO charges,345.0,d,1.25,86.7
11,2001825261,8904223818669,1,Prepaid,301,301,0.0,240,0.240,1091121981575,1.6,d,Forward and RTO charges,345.0,d,1.25,86.7
12,2001825261,SACHETS001,1,Prepaid,350,350,0.0,10,0.010,1091121981575,1.6,d,Forward and RTO charges,345.0,d,1.25,86.7

In [1159]:
#Expected charge for X in e zone
fwd_fxd = 56.6
fwd_add = 55.5
rto_fxd = 50.7
rto_add = 55.50
weight_slab = zonexe["weight slab as per X (kg)"]
add_weight = (weight_slab-1.5)/1.5
zonexe["expected charges by X in Rs"] = 0
zonexe["expected charges by X in Rs"] = np.where(zonexe['Type of Shipment'] == 'Forward charges', (fwd_fxd + add_weight*fwd_add), zonexe["expected charges by X in Rs"])
zonexe["expected charges by X in Rs"] = np.where(zonexe["Type of Shipment"]== "Forward and RTO charges",(fwd_fxd + rto_fxd + add_weight*(fwd_add + rto_add)) ,zonexe["expected charges by X in Rs"])
zonexe.head()

<ipython-input-1159-18c1986d45ad>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zonexe["expected charges by X in Rs"] = 0
<ipython-input-1159-18c1986d45ad>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zonexe["expected charges by X in Rs"] = np.where(zonexe['Type of Shipment'] == 'Forward charges', (fwd_fxd + add_weight*fwd_add), zonexe["expected charges by X in Rs"])
<ipython-input-1159-18c1986d45ad>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  zonexe["expected charges by X in Rs"] = np.where(zonexe["Type of Shipment"]== "Forward and RTO charges",(fwd_fxd + rto_fxd + add_weight*(fwd_add + rto_add)) ,zonexe["expected charges by X in Rs"])

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs,COD charges in Rs as per X,Weight (g),total_weight in KG as per X,AWB Code,total weight as per courier,Zone as per courier,Type of Shipment,Billing Amount (Rs.),Zone as per X,weight slab as per X (kg),expected charges by X in Rs
0,2001827036,8904223818706,1,COD,233,233,15.0,127,0.127,1091122418320,1.6,b,Forward charges,117.9,e,1.5,56.6
1,2001827036,8904223819093,1,COD,233,233,15.0,150,0.150,1091122418320,1.6,b,Forward charges,117.9,e,1.5,56.6
2,2001827036,8904223819109,1,COD,233,233,15.0,100,0.100,1091122418320,1.6,b,Forward charges,117.9,e,1.5,56.6
3,2001827036,8904223818430,1,COD,470,470,23.5,165,0.165,1091122418320,1.6,b,Forward charges,117.9,e,1.5,56.6
4,2001827036,8904223819277,1,COD,233,233,15.0,350,0.350,1091122418320,1.6,b,Forward charges,117.9,e,1.5,56.6

In [1160]:
data = pd.concat([zonexb,zonexd,zonexe])
data.head()

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs,COD charges in Rs as per X,Weight (g),total_weight in KG as per X,AWB Code,total weight as per courier,Zone as per courier,Type of Shipment,Billing Amount (Rs.),Zone as per X,weight slab as per X (kg),expected charges by X in Rs
16,2001822466,8904223819468,2,COD,1205,2410,120.5,240,0.480,1091121305541,1.1,d,Forward charges,135.0,b,0.5,33.0
17,2001822466,8904223819291,8,COD,7814,62512,3125.6,112,0.896,1091121305541,1.1,d,Forward charges,135.0,b,1.0,61.3
18,2001821995,8904223819130,1,Prepaid,251,251,0.0,350,0.350,1091121183730,0.5,d,Forward charges,45.4,b,0.5,33.0
19,2001821995,8904223818706,1,Prepaid,233,233,0.0,127,0.127,1091121183730,0.5,d,Forward charges,45.4,b,0.5,33.0
20,2001821766,8904223818591,2,COD,473,946,47.3,120,0.240,1091121034641,0.2,d,Forward charges,63.4,b,0.5,33.0

In [1161]:
data.shape

(400, 17)

In [1162]:
data["Zone as per courier"].unique()

array(['d', 'b', 'e'], dtype=object)

In [1163]:
c_d = data[data["Zone as per courier"] == "d"]
c_b = data[data["Zone as per courier"] == "b"]
c_e = data[data["Zone as per courier"] == "e"]

In [1164]:
print(c_d.shape,c_b.shape,c_e.shape)

(309, 17) (86, 17) (5, 17)

## calculations of weight slab and total price

In [1165]:
# weight slab for zone_b as per Courier
def weight_slab(weight):
    i = round(weight % 1, 1)
    if i == 0.0:
        return weight
    elif i > 0.5:
        return int(weight)+1
    else:
        return int(weight)+0.5

c_b["Weight slab charged by Courier in kg"] = c_b["total weight as per courier"].apply(weight_slab)
c_b.head()

<ipython-input-1165-826f45bf0a66>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_b["Weight slab charged by Courier in kg"] = c_b["total weight as per courier"].apply(weight_slab)

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs,COD charges in Rs as per X,Weight (g),total_weight in KG as per X,AWB Code,total weight as per courier,Zone as per courier,Type of Shipment,Billing Amount (Rs.),Zone as per X,weight slab as per X (kg),expected charges by X in Rs,Weight slab charged by Courier in kg
52,2001817093,8904223816214,1,COD,402,402,20.10,120,0.120,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5
53,2001817093,8904223818874,1,COD,922,922,46.10,100,0.100,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5
54,2001817093,8904223819512,1,COD,534,534,26.70,210,0.210,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5
55,2001817093,8904223818881,1,COD,819,819,40.95,140,0.140,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5
56,2001817093,8904223819291,2,COD,1954,3908,195.40,112,0.224,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5

In [1166]:
# weight slab for zone_d as per courier
def weight_slab(weight):
    i = round(weight % 1.25, 2)
    if i == 0.00:
        return weight
    elif weight<1.25:
        return 1.25
    else:
        return (weight//1.25)*1.25+1.25

c_d["Weight slab charged by Courier in kg"] = c_d["total weight as per courier"].apply(weight_slab)
c_d.head()

<ipython-input-1166-bfabc385ce1b>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_d["Weight slab charged by Courier in kg"] = c_d["total weight as per courier"].apply(weight_slab)

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs,COD charges in Rs as per X,Weight (g),total_weight in KG as per X,AWB Code,total weight as per courier,Zone as per courier,Type of Shipment,Billing Amount (Rs.),Zone as per X,weight slab as per X (kg),expected charges by X in Rs,Weight slab charged by Courier in kg
16,2001822466,8904223819468,2,COD,1205,2410,120.5,240,0.480,1091121305541,1.1,d,Forward charges,135.0,b,0.5,33.0,1.25
17,2001822466,8904223819291,8,COD,7814,62512,3125.6,112,0.896,1091121305541,1.1,d,Forward charges,135.0,b,1.0,61.3,1.25
18,2001821995,8904223819130,1,Prepaid,251,251,0.0,350,0.350,1091121183730,0.5,d,Forward charges,45.4,b,0.5,33.0,1.25
19,2001821995,8904223818706,1,Prepaid,233,233,0.0,127,0.127,1091121183730,0.5,d,Forward charges,45.4,b,0.5,33.0,1.25
20,2001821766,8904223818591,2,COD,473,946,47.3,120,0.240,1091121034641,0.2,d,Forward charges,63.4,b,0.5,33.0,1.25

In [1167]:
# weight slab for zone_e as per courier
def weight_slab(weight):
    i = round(weight % 1.5, 2)
    if i == 0.00:
        return weight
    elif weight<1.5:
        return 1.5
    else:
        return (weight//1.5)*1.5+1.5

c_e["Weight slab charged by Courier in kg"] = c_e["total weight as per courier"].apply(weight_slab)
c_e.head()

<ipython-input-1167-34d913e9917e>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c_e["Weight slab charged by Courier in kg"] = c_e["total weight as per courier"].apply(weight_slab)

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs,COD charges in Rs as per X,Weight (g),total_weight in KG as per X,AWB Code,total weight as per courier,Zone as per courier,Type of Shipment,Billing Amount (Rs.),Zone as per X,weight slab as per X (kg),expected charges by X in Rs,Weight slab charged by Courier in kg
47,2001818390,8904223819147,1,COD,233,233,15.00,240,0.240,1091120014461,0.8,e,Forward and RTO charges,213.5,e,1.5,107.3,1.5
48,2001818390,8904223818935,4,COD,932,3728,186.40,120,0.480,1091120014461,0.8,e,Forward and RTO charges,213.5,e,1.5,107.3,1.5
49,2001818390,8904223818683,1,COD,999,999,49.95,121,0.121,1091120014461,0.8,e,Forward and RTO charges,213.5,e,1.5,107.3,1.5
225,2001808295,8904223819161,1,COD,810,810,40.50,115,0.115,1091117435661,0.2,e,Forward and RTO charges,127.3,e,1.5,107.3,1.5
226,2001808295,8904223819260,1,COD,676,676,33.80,130,0.130,1091117435661,0.2,e,Forward and RTO charges,127.3,e,1.5,107.3,1.5

In [1168]:
data_done = pd.concat([c_b,c_d,c_e])
data_done.head()

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs,COD charges in Rs as per X,Weight (g),total_weight in KG as per X,AWB Code,total weight as per courier,Zone as per courier,Type of Shipment,Billing Amount (Rs.),Zone as per X,weight slab as per X (kg),expected charges by X in Rs,Weight slab charged by Courier in kg
52,2001817093,8904223816214,1,COD,402,402,20.10,120,0.120,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5
53,2001817093,8904223818874,1,COD,922,922,46.10,100,0.100,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5
54,2001817093,8904223819512,1,COD,534,534,26.70,210,0.210,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5
55,2001817093,8904223818881,1,COD,819,819,40.95,140,0.140,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5
56,2001817093,8904223819291,2,COD,1954,3908,195.40,112,0.224,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5

In [1169]:
data_done["Expected Charges as per X in Rs"] = data_done["expected charges by X in Rs"]+data_done["COD charges in Rs as per X"]
data_done.head()

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs,COD charges in Rs as per X,Weight (g),total_weight in KG as per X,AWB Code,total weight as per courier,Zone as per courier,Type of Shipment,Billing Amount (Rs.),Zone as per X,weight slab as per X (kg),expected charges by X in Rs,Weight slab charged by Courier in kg,Expected Charges as per X in Rs
52,2001817093,8904223816214,1,COD,402,402,20.10,120,0.120,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5,73.60
53,2001817093,8904223818874,1,COD,922,922,46.10,100,0.100,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5,99.60
54,2001817093,8904223819512,1,COD,534,534,26.70,210,0.210,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5,80.20
55,2001817093,8904223818881,1,COD,819,819,40.95,140,0.140,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5,94.45
56,2001817093,8904223819291,2,COD,1954,3908,195.40,112,0.224,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5,248.90

In [1170]:
data_done.rename(columns= {"Billing Amount (Rs.)":"Charges Billed by Courier Company in Rs"}, inplace = True)
data_done["Difference Between Expected Charges and Billed Charges (Rs.)"] = data_done["Charges Billed by Courier Company in Rs"] - data_done["Expected Charges as per X in Rs"]
data_done

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),total order price in Rs,COD charges in Rs as per X,Weight (g),total_weight in KG as per X,AWB Code,total weight as per courier,Zone as per courier,Type of Shipment,Charges Billed by Courier Company in Rs,Zone as per X,weight slab as per X (kg),expected charges by X in Rs,Weight slab charged by Courier in kg,Expected Charges as per X in Rs,Difference Between Expected Charges and Billed Charges (Rs.)
52,2001817093,8904223816214,1,COD,402,402,20.10,120,0.120,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5,73.60,92.50
53,2001817093,8904223818874,1,COD,922,922,46.10,100,0.100,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5,99.60,66.50
54,2001817093,8904223819512,1,COD,534,534,26.70,210,0.210,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5,80.20,85.90
55,2001817093,8904223818881,1,COD,819,819,40.95,140,0.140,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5,94.45,71.65
56,2001817093,8904223819291,2,COD,1954,3908,195.40,112,0.224,1091121485824,1.3,b,Forward and RTO charges,166.1,b,0.5,53.5,1.5,248.90,-82.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,2001818390,8904223819147,1,COD,233,233,15.00,240,0.240,1091120014461,0.8,e,Forward and RTO charges,213.5,e,1.5,107.3,1.5,122.30,91.20
48,2001818390,8904223818935,4,COD,932,3728,186.40,120,0.480,1091120014461,0.8,e,Forward and RTO charges,213.5,e,1.5,107.3,1.5,293.70,-80.20
49,2001818390,8904223818683,1,COD,999,999,49.95,121,0.121,1091120014461,0.8,e,Forward and RTO charges,213.5,e,1.5,107.3,1.5,157.25,56.25
225,2001808295,8904223819161,1,COD,810,810,40.50,115,0.115,1091117435661,0.2,e,Forward and RTO charges,127.3,e,1.5,107.3,1.5,147.80,-20.50
226,2001808295,8904223819260,1,COD,676,676,33.80,130,0.130,1091117435661,0.2,e,Forward and RTO charges,127.3,e,1.5,107.3,1.5,141.10,-13.80



> Preparing worksheet 2

In [1171]:
data_done = data_done.drop(columns=["Type of Shipment" , "Payment Mode" , "Item Price(Per Qty.)" , "total order price in Rs","COD charges in Rs as per X","Weight (g)","SKU","Order Qty","expected charges by X in Rs"])
data_done

,Order ID,total_weight in KG as per X,AWB Code,total weight as per courier,Zone as per courier,Charges Billed by Courier Company in Rs,Zone as per X,weight slab as per X (kg),Weight slab charged by Courier in kg,Expected Charges as per X in Rs,Difference Between Expected Charges and Billed Charges (Rs.)
52,2001817093,0.120,1091121485824,1.3,b,166.1,b,0.5,1.5,73.60,92.50
53,2001817093,0.100,1091121485824,1.3,b,166.1,b,0.5,1.5,99.60,66.50
54,2001817093,0.210,1091121485824,1.3,b,166.1,b,0.5,1.5,80.20,85.90
55,2001817093,0.140,1091121485824,1.3,b,166.1,b,0.5,1.5,94.45,71.65
56,2001817093,0.224,1091121485824,1.3,b,166.1,b,0.5,1.5,248.90,-82.80
...,...,...,...,...,...,...,...,...,...,...,...
47,2001818390,0.240,1091120014461,0.8,e,213.5,e,1.5,1.5,122.30,91.20
48,2001818390,0.480,1091120014461,0.8,e,213.5,e,1.5,1.5,293.70,-80.20
49,2001818390,0.121,1091120014461,0.8,e,213.5,e,1.5,1.5,157.25,56.25
225,2001808295,0.115,1091117435661,0.2,e,127.3,e,1.5,1.5,147.80,-20.50
226,2001808295,0.130,1091117435661,0.2,e,127.3,e,1.5,1.5,141.10,-13.80

In [1172]:
output = data_done[['AWB Code','Order ID','total_weight in KG as per X','weight slab as per X (kg)','total weight as per courier','Weight slab charged by Courier in kg','Zone as per X','Zone as per courier','Expected Charges as per X in Rs','Charges Billed by Courier Company in Rs','Difference Between Expected Charges and Billed Charges (Rs.)']]

In [1173]:
output

,AWB Code,Order ID,total_weight in KG as per X,weight slab as per X (kg),total weight as per courier,Weight slab charged by Courier in kg,Zone as per X,Zone as per courier,Expected Charges as per X in Rs,Charges Billed by Courier Company in Rs,Difference Between Expected Charges and Billed Charges (Rs.)
52,1091121485824,2001817093,0.120,0.5,1.3,1.5,b,b,73.60,166.1,92.50
53,1091121485824,2001817093,0.100,0.5,1.3,1.5,b,b,99.60,166.1,66.50
54,1091121485824,2001817093,0.210,0.5,1.3,1.5,b,b,80.20,166.1,85.90
55,1091121485824,2001817093,0.140,0.5,1.3,1.5,b,b,94.45,166.1,71.65
56,1091121485824,2001817093,0.224,0.5,1.3,1.5,b,b,248.90,166.1,-82.80
...,...,...,...,...,...,...,...,...,...,...,...
47,1091120014461,2001818390,0.240,1.5,0.8,1.5,e,e,122.30,213.5,91.20
48,1091120014461,2001818390,0.480,1.5,0.8,1.5,e,e,293.70,213.5,-80.20
49,1091120014461,2001818390,0.121,1.5,0.8,1.5,e,e,157.25,213.5,56.25
225,1091117435661,2001808295,0.115,1.5,0.2,1.5,e,e,147.80,127.3,-20.50
226,1091117435661,2001808295,0.130,1.5,0.2,1.5,e,e,141.10,127.3,-13.80

In [1174]:
output.reset_index(drop = True, inplace = True)

In [1175]:
output_file = output.rename(columns={'total_weight in KG as per X':'Total weight as per X (KG)','weight slab as per X (kg)':'Weight slab as per X (KG)','total weight as per courier':'Total weight as per Courier Company (KG)','Weight slab charged by Courier in kg':'Weight slab charged by Courier Company (KG)',
                       'Zone as per X':'Delivery Zone as per X','Zone as per courier':'Delivery Zone charged by Courier Company','Expected Charges as per X in Rs':'Expected Charge as per X (Rs.)',
                       'Charges Billed by Courier Company in Rs':'Charges Billed by Courier Company (Rs.)','Difference Between Expected Charges and Billed Charges (Rs.)':'Difference Between Expected Charges and Billed Charges (Rs.)'})
output_file

,AWB Code,Order ID,Total weight as per X (KG),Weight slab as per X (KG),Total weight as per Courier Company (KG),Weight slab charged by Courier Company (KG),Delivery Zone as per X,Delivery Zone charged by Courier Company,Expected Charge as per X (Rs.),Charges Billed by Courier Company (Rs.),Difference Between Expected Charges and Billed Charges (Rs.)
0,1091121485824,2001817093,0.120,0.5,1.3,1.5,b,b,73.60,166.1,92.50
1,1091121485824,2001817093,0.100,0.5,1.3,1.5,b,b,99.60,166.1,66.50
2,1091121485824,2001817093,0.210,0.5,1.3,1.5,b,b,80.20,166.1,85.90
3,1091121485824,2001817093,0.140,0.5,1.3,1.5,b,b,94.45,166.1,71.65
4,1091121485824,2001817093,0.224,0.5,1.3,1.5,b,b,248.90,166.1,-82.80
...,...,...,...,...,...,...,...,...,...,...,...
395,1091120014461,2001818390,0.240,1.5,0.8,1.5,e,e,122.30,213.5,91.20
396,1091120014461,2001818390,0.480,1.5,0.8,1.5,e,e,293.70,213.5,-80.20
397,1091120014461,2001818390,0.121,1.5,0.8,1.5,e,e,157.25,213.5,56.25
398,1091117435661,2001808295,0.115,1.5,0.2,1.5,e,e,147.80,127.3,-20.50
399,1091117435661,2001808295,0.130,1.5,0.2,1.5,e,e,141.10,127.3,-13.80



> preparing worksheet 1

In [1176]:
# Calculate the total orders in each category
total_correctly_charged = len(output_file[output_file['Difference Between Expected Charges and Billed Charges (Rs.)'] == 0])
total_overcharged = len(output_file[output_file['Difference Between Expected Charges and Billed Charges (Rs.)'] > 0])
total_undercharged = len(output_file[output_file['Difference Between Expected Charges and Billed Charges (Rs.)'] < 0])

# Calculate the total amount in each category
amount_overcharged = abs(output_file[output_file['Difference Between Expected Charges and Billed Charges (Rs.)']> 0]['Difference Between Expected Charges and Billed Charges (Rs.)'].sum())
amount_undercharged = output_file[output_file['Difference Between Expected Charges and Billed Charges (Rs.)']< 0]['Difference Between Expected Charges and Billed Charges (Rs.)'].sum()
amount_correctly_charged = output_file[output_file['Difference Between Expected Charges and Billed Charges (Rs.)']== 0]['Expected Charge as per X (Rs.)'].sum()

# Create a new DataFrame for the summary
summary_data = {'Description': ['Total Orders where X has been correctly charged',
                                'Total Orders where X has been overcharged',
                                'Total Orders where X has been undercharged'],
                'Count': [total_correctly_charged, total_overcharged, total_undercharged],
                'Amount (Rs.)': [amount_correctly_charged, amount_overcharged, amount_undercharged]}

df_summary = pd.DataFrame(summary_data)

print(df_summary)

                                       Description  Count  Amount (Rs.)
0  Total Orders where X has been correctly charged     11         462.2
1        Total Orders where X has been overcharged    348       26820.7
2       Total Orders where X has been undercharged     41       -7291.0

In [1177]:
with pd.ExcelWriter("Cointab_Azad_Singh_S_assignment.xlsx") as writer:
    df_summary.to_excel(writer, sheet_name='Output Data 1', index=False)
    output_file.to_excel(writer, sheet_name='Output Data 2', index=False)